"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.netgw_public import NetgwPublic
from h1.model.tag_array import TagArray
globals()['NetgwPublic'] = NetgwPublic
globals()['TagArray'] = TagArray
from h1.model.networking_project_netgw_create import NetworkingProjectNetgwCreate


class TestNetworkingProjectNetgwCreate(unittest.TestCase):
    """NetworkingProjectNetgwCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkingProjectNetgwCreate(self):
        """Test NetworkingProjectNetgwCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkingProjectNetgwCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
