"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.provider_link import ProviderLink


class TestProviderLink(unittest.TestCase):
    """ProviderLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderLink(self):
        """Test ProviderLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProviderLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
