"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.storage_project_iso_detach import StorageProjectIsoDetach


class TestStorageProjectIsoDetach(unittest.TestCase):
    """StorageProjectIsoDetach unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageProjectIsoDetach(self):
        """Test StorageProjectIsoDetach"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageProjectIsoDetach()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
