"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.iam_permission import IamPermission
globals()['IamPermission'] = IamPermission
from h1.model.iam_permission_array import IamPermissionArray


class TestIamPermissionArray(unittest.TestCase):
    """IamPermissionArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIamPermissionArray(self):
        """Test IamPermissionArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IamPermissionArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
