"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.dns_record_array import DnsRecordArray
globals()['DnsRecordArray'] = DnsRecordArray
from h1.model.dns_recordset import DnsRecordset


class TestDnsRecordset(unittest.TestCase):
    """DnsRecordset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDnsRecordset(self):
        """Test DnsRecordset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DnsRecordset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
