"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.recovery_project_plan_create_retention import RecoveryProjectPlanCreateRetention
from h1.model.recovery_project_plan_create_window import RecoveryProjectPlanCreateWindow
from h1.model.tag_array import TagArray
globals()['RecoveryProjectPlanCreateRetention'] = RecoveryProjectPlanCreateRetention
globals()['RecoveryProjectPlanCreateWindow'] = RecoveryProjectPlanCreateWindow
globals()['TagArray'] = TagArray
from h1.model.recovery_project_plan_create import RecoveryProjectPlanCreate


class TestRecoveryProjectPlanCreate(unittest.TestCase):
    """RecoveryProjectPlanCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoveryProjectPlanCreate(self):
        """Test RecoveryProjectPlanCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoveryProjectPlanCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
