"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.container_project_registry_transfer import ContainerProjectRegistryTransfer


class TestContainerProjectRegistryTransfer(unittest.TestCase):
    """ContainerProjectRegistryTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerProjectRegistryTransfer(self):
        """Test ContainerProjectRegistryTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerProjectRegistryTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
