# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import h1
from h1.api.iam_project_api import IamProjectApi  # noqa: E501
from h1.rest import ApiException


class TestIamProjectApi(unittest.TestCase):
    """IamProjectApi unit test stubs"""

    def setUp(self):
        self.api = h1.api.iam_project_api.IamProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_iam_project_billing_list(self):
        """Test case for iam_project_billing_list

        List iam/project.billing  # noqa: E501
        """
        pass

    def test_iam_project_create(self):
        """Test case for iam_project_create

        Create iam/project  # noqa: E501
        """
        pass

    def test_iam_project_credential_store_create(self):
        """Test case for iam_project_credential_store_create

        Create iam/project.credentialStore  # noqa: E501
        """
        pass

    def test_iam_project_credential_store_delete(self):
        """Test case for iam_project_credential_store_delete

        Delete iam/project.credentialStore  # noqa: E501
        """
        pass

    def test_iam_project_credential_store_get(self):
        """Test case for iam_project_credential_store_get

        Get iam/project.credentialStore  # noqa: E501
        """
        pass

    def test_iam_project_credential_store_list(self):
        """Test case for iam_project_credential_store_list

        List iam/project.credentialStore  # noqa: E501
        """
        pass

    def test_iam_project_credential_store_patch(self):
        """Test case for iam_project_credential_store_patch

        Update iam/project.credentialStore  # noqa: E501
        """
        pass

    def test_iam_project_delete(self):
        """Test case for iam_project_delete

        Delete iam/project  # noqa: E501
        """
        pass

    def test_iam_project_event_get(self):
        """Test case for iam_project_event_get

        Get iam/project.event  # noqa: E501
        """
        pass

    def test_iam_project_event_list(self):
        """Test case for iam_project_event_list

        List iam/project.event  # noqa: E501
        """
        pass

    def test_iam_project_get(self):
        """Test case for iam_project_get

        Get iam/project  # noqa: E501
        """
        pass

    def test_iam_project_invitation_accept(self):
        """Test case for iam_project_invitation_accept

        Accept iam/project.invitation  # noqa: E501
        """
        pass

    def test_iam_project_invitation_delete(self):
        """Test case for iam_project_invitation_delete

        Delete iam/project.invitation  # noqa: E501
        """
        pass

    def test_iam_project_invitation_get(self):
        """Test case for iam_project_invitation_get

        Get iam/project.invitation  # noqa: E501
        """
        pass

    def test_iam_project_invitation_list(self):
        """Test case for iam_project_invitation_list

        List iam/project.invitation  # noqa: E501
        """
        pass

    def test_iam_project_invoice_list(self):
        """Test case for iam_project_invoice_list

        List iam/project.invoice  # noqa: E501
        """
        pass

    def test_iam_project_list(self):
        """Test case for iam_project_list

        List iam/project  # noqa: E501
        """
        pass

    def test_iam_project_ownership_create(self):
        """Test case for iam_project_ownership_create

        Create iam/project.ownership  # noqa: E501
        """
        pass

    def test_iam_project_ownership_delete(self):
        """Test case for iam_project_ownership_delete

        Delete iam/project.ownership  # noqa: E501
        """
        pass

    def test_iam_project_ownership_get(self):
        """Test case for iam_project_ownership_get

        Get iam/project.ownership  # noqa: E501
        """
        pass

    def test_iam_project_ownership_list(self):
        """Test case for iam_project_ownership_list

        List iam/project.ownership  # noqa: E501
        """
        pass

    def test_iam_project_payment_list(self):
        """Test case for iam_project_payment_list

        List iam/project.payment  # noqa: E501
        """
        pass

    def test_iam_project_proforma_list(self):
        """Test case for iam_project_proforma_list

        List iam/project.proforma  # noqa: E501
        """
        pass

    def test_iam_project_quota_get(self):
        """Test case for iam_project_quota_get

        Get iam/project.quota  # noqa: E501
        """
        pass

    def test_iam_project_quota_limit_patch(self):
        """Test case for iam_project_quota_limit_patch

        Update iam/project.limit  # noqa: E501
        """
        pass

    def test_iam_project_quota_list(self):
        """Test case for iam_project_quota_list

        List iam/project.quota  # noqa: E501
        """
        pass

    def test_iam_project_service_get(self):
        """Test case for iam_project_service_get

        Get iam/project.service  # noqa: E501
        """
        pass

    def test_iam_project_service_list(self):
        """Test case for iam_project_service_list

        List iam/project.service  # noqa: E501
        """
        pass

    def test_iam_project_tag_create(self):
        """Test case for iam_project_tag_create

        Create iam/project.tag  # noqa: E501
        """
        pass

    def test_iam_project_tag_delete(self):
        """Test case for iam_project_tag_delete

        Delete iam/project.tag  # noqa: E501
        """
        pass

    def test_iam_project_tag_get(self):
        """Test case for iam_project_tag_get

        Get iam/project.tag  # noqa: E501
        """
        pass

    def test_iam_project_tag_list(self):
        """Test case for iam_project_tag_list

        List iam/project.tag  # noqa: E501
        """
        pass

    def test_iam_project_tag_put(self):
        """Test case for iam_project_tag_put

        Replace iam/project.tag  # noqa: E501
        """
        pass

    def test_iam_project_threshold_create(self):
        """Test case for iam_project_threshold_create

        Create iam/project.threshold  # noqa: E501
        """
        pass

    def test_iam_project_threshold_delete(self):
        """Test case for iam_project_threshold_delete

        Delete iam/project.threshold  # noqa: E501
        """
        pass

    def test_iam_project_threshold_get(self):
        """Test case for iam_project_threshold_get

        Get iam/project.threshold  # noqa: E501
        """
        pass

    def test_iam_project_threshold_list(self):
        """Test case for iam_project_threshold_list

        List iam/project.threshold  # noqa: E501
        """
        pass

    def test_iam_project_transfer(self):
        """Test case for iam_project_transfer

        Transfer iam/project  # noqa: E501
        """
        pass

    def test_iam_project_update(self):
        """Test case for iam_project_update

        Update iam/project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
