"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.dns_record import DnsRecord
globals()['DnsRecord'] = DnsRecord
from h1.model.dns_record_array import DnsRecordArray


class TestDnsRecordArray(unittest.TestCase):
    """DnsRecordArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDnsRecordArray(self):
        """Test DnsRecordArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DnsRecordArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
