"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import h1
from h1.api.storage_project_bucket_api import StorageProjectBucketApi  # noqa: E501


class TestStorageProjectBucketApi(unittest.TestCase):
    """StorageProjectBucketApi unit test stubs"""

    def setUp(self):
        self.api = StorageProjectBucketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_storage_project_bucket_get(self):
        """Test case for storage_project_bucket_get

        Get storage/bucket  # noqa: E501
        """
        pass

    def test_storage_project_bucket_list(self):
        """Test case for storage_project_bucket_list

        List storage/bucket  # noqa: E501
        """
        pass

    def test_storage_project_bucket_object_delete(self):
        """Test case for storage_project_bucket_object_delete

        Delete storage/bucket.object  # noqa: E501
        """
        pass

    def test_storage_project_bucket_object_download(self):
        """Test case for storage_project_bucket_object_download

        Download storage/bucket.object  # noqa: E501
        """
        pass

    def test_storage_project_bucket_object_get(self):
        """Test case for storage_project_bucket_object_get

        Get storage/bucket.object  # noqa: E501
        """
        pass

    def test_storage_project_bucket_object_list(self):
        """Test case for storage_project_bucket_object_list

        List storage/bucket.object  # noqa: E501
        """
        pass

    def test_storage_project_bucket_upload(self):
        """Test case for storage_project_bucket_upload

        Upload storage/bucket  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
