"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.database_project_instance_transfer import DatabaseProjectInstanceTransfer


class TestDatabaseProjectInstanceTransfer(unittest.TestCase):
    """DatabaseProjectInstanceTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatabaseProjectInstanceTransfer(self):
        """Test DatabaseProjectInstanceTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DatabaseProjectInstanceTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
