# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import h1-client-python
from h1-client-python.models.invoice import Invoice  # noqa: E501
from h1-client-python.rest import ApiException

class TestInvoice(unittest.TestCase):
    """Invoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Invoice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = h1-client-python.models.invoice.Invoice()  # noqa: E501
        if include_optional :
            return Invoice(
                id = '0', 
                additional_info = '0', 
                corrections = [
                    '0'
                    ], 
                invoice_info = '0', 
                invoice_no = '0', 
                issue_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                payments = [
                    '0'
                    ], 
                seller = h1-client-python.models.invoice_seller.invoice_seller(
                    company = '0', 
                    address = h1-client-python.models.invoice_seller_address.invoice_seller_address(
                        street = '0', 
                        zipcode = '0', 
                        city = '0', 
                        country = '0', ), 
                    nip = '0', ), 
                items = [
                    h1-client-python.models.invoice_items.invoice_items(
                        name = '0', 
                        price = '0', 
                        netto = '0', 
                        brutto = '0', 
                        vat_amount = '0', 
                        vat_rate = '0', 
                        quantity = 1.337, )
                    ], 
                buyer = h1-client-python.models.invoice_buyer.invoice_buyer(
                    company = '0', 
                    address = h1-client-python.models.invoice_buyer_address.invoice_buyer_address(
                        street = '0', 
                        zipcode = '0', 
                        city = '0', 
                        country = '0', ), 
                    nip = '0', 
                    email = '0', ), 
                type = 'vat', 
                summary = '0', 
                project = '0', 
                duplicate = h1-client-python.models.invoice_duplicate.invoice_duplicate(
                    created_on = '0', 
                    id = '0', ), 
                uri = '0', 
                array__ = '0'
            )
        else :
            return Invoice(
        )

    def testInvoice(self):
        """Test Invoice"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
