"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.service_billing_price import ServiceBillingPrice
from h1.model.service_billing_reservations import ServiceBillingReservations
globals()['ServiceBillingPrice'] = ServiceBillingPrice
globals()['ServiceBillingReservations'] = ServiceBillingReservations
from h1.model.service_billing import ServiceBilling


class TestServiceBilling(unittest.TestCase):
    """ServiceBilling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceBilling(self):
        """Test ServiceBilling"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceBilling()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
