"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.service_display_unit import ServiceDisplayUnit


class TestServiceDisplayUnit(unittest.TestCase):
    """ServiceDisplayUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceDisplayUnit(self):
        """Test ServiceDisplayUnit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceDisplayUnit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
