# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import h1-client-python
from h1-client-python.api.storage_project_image_api import StorageProjectImageApi  # noqa: E501
from h1-client-python.rest import ApiException


class TestStorageProjectImageApi(unittest.TestCase):
    """StorageProjectImageApi unit test stubs"""

    def setUp(self):
        self.api = h1-client-python.api.storage_project_image_api.StorageProjectImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_storage_project_image_create(self):
        """Test case for storage_project_image_create

        Create storage/image  # noqa: E501
        """
        pass

    def test_storage_project_image_delete(self):
        """Test case for storage_project_image_delete

        Delete storage/image  # noqa: E501
        """
        pass

    def test_storage_project_image_disk_list(self):
        """Test case for storage_project_image_disk_list

        List storage/image.disk  # noqa: E501
        """
        pass

    def test_storage_project_image_event_get(self):
        """Test case for storage_project_image_event_get

        Get storage/image.event  # noqa: E501
        """
        pass

    def test_storage_project_image_event_list(self):
        """Test case for storage_project_image_event_list

        List storage/image.event  # noqa: E501
        """
        pass

    def test_storage_project_image_get(self):
        """Test case for storage_project_image_get

        Get storage/image  # noqa: E501
        """
        pass

    def test_storage_project_image_list(self):
        """Test case for storage_project_image_list

        List storage/image  # noqa: E501
        """
        pass

    def test_storage_project_image_service_get(self):
        """Test case for storage_project_image_service_get

        Get storage/image.service  # noqa: E501
        """
        pass

    def test_storage_project_image_service_list(self):
        """Test case for storage_project_image_service_list

        List storage/image.service  # noqa: E501
        """
        pass

    def test_storage_project_image_tag_create(self):
        """Test case for storage_project_image_tag_create

        Create storage/image.tag  # noqa: E501
        """
        pass

    def test_storage_project_image_tag_delete(self):
        """Test case for storage_project_image_tag_delete

        Delete storage/image.tag  # noqa: E501
        """
        pass

    def test_storage_project_image_tag_get(self):
        """Test case for storage_project_image_tag_get

        Get storage/image.tag  # noqa: E501
        """
        pass

    def test_storage_project_image_tag_list(self):
        """Test case for storage_project_image_tag_list

        List storage/image.tag  # noqa: E501
        """
        pass

    def test_storage_project_image_tag_put(self):
        """Test case for storage_project_image_tag_put

        Replace storage/image.tag  # noqa: E501
        """
        pass

    def test_storage_project_image_transfer(self):
        """Test case for storage_project_image_transfer

        Transfer storage/image  # noqa: E501
        """
        pass

    def test_storage_project_image_update(self):
        """Test case for storage_project_image_update

        Update storage/image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
