# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import h1
from h1.api.support_project_ticket_api import SupportProjectTicketApi  # noqa: E501
from h1.rest import ApiException


class TestSupportProjectTicketApi(unittest.TestCase):
    """SupportProjectTicketApi unit test stubs"""

    def setUp(self):
        self.api = h1.api.support_project_ticket_api.SupportProjectTicketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_support_project_ticket_close(self):
        """Test case for support_project_ticket_close

        Close support/ticket  # noqa: E501
        """
        pass

    def test_support_project_ticket_create(self):
        """Test case for support_project_ticket_create

        Create support/ticket  # noqa: E501
        """
        pass

    def test_support_project_ticket_get(self):
        """Test case for support_project_ticket_get

        Get support/ticket  # noqa: E501
        """
        pass

    def test_support_project_ticket_list(self):
        """Test case for support_project_ticket_list

        List support/ticket  # noqa: E501
        """
        pass

    def test_support_project_ticket_message_create(self):
        """Test case for support_project_ticket_message_create

        Create support/ticket.message  # noqa: E501
        """
        pass

    def test_support_project_ticket_message_get(self):
        """Test case for support_project_ticket_message_get

        Get support/ticket.message  # noqa: E501
        """
        pass

    def test_support_project_ticket_message_list(self):
        """Test case for support_project_ticket_message_list

        List support/ticket.message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
