"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.event_base import EventBase
globals()['EventBase'] = EventBase
from h1.model.event_base_array import EventBaseArray


class TestEventBaseArray(unittest.TestCase):
    """EventBaseArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventBaseArray(self):
        """Test EventBaseArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventBaseArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
