"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.tag_array import TagArray
globals()['TagArray'] = TagArray
from h1.model.networking_project_netadp_create import NetworkingProjectNetadpCreate


class TestNetworkingProjectNetadpCreate(unittest.TestCase):
    """NetworkingProjectNetadpCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkingProjectNetadpCreate(self):
        """Test NetworkingProjectNetadpCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkingProjectNetadpCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
