"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.storage_object import StorageObject


class TestStorageObject(unittest.TestCase):
    """StorageObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageObject(self):
        """Test StorageObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
