"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import h1
from h1.api.provider_project_development_api import ProviderProjectDevelopmentApi  # noqa: E501


class TestProviderProjectDevelopmentApi(unittest.TestCase):
    """ProviderProjectDevelopmentApi unit test stubs"""

    def setUp(self):
        self.api = ProviderProjectDevelopmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_provider_project_development_connect_get(self):
        """Test case for provider_project_development_connect_get

        Get provider/development.connect  # noqa: E501
        """
        pass

    def test_provider_project_development_connect_list(self):
        """Test case for provider_project_development_connect_list

        List provider/development.connect  # noqa: E501
        """
        pass

    def test_provider_project_development_create(self):
        """Test case for provider_project_development_create

        Create provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_credential_create(self):
        """Test case for provider_project_development_credential_create

        Create provider/development.credential  # noqa: E501
        """
        pass

    def test_provider_project_development_credential_delete(self):
        """Test case for provider_project_development_credential_delete

        Delete provider/development.credential  # noqa: E501
        """
        pass

    def test_provider_project_development_credential_get(self):
        """Test case for provider_project_development_credential_get

        Get provider/development.credential  # noqa: E501
        """
        pass

    def test_provider_project_development_credential_list(self):
        """Test case for provider_project_development_credential_list

        List provider/development.credential  # noqa: E501
        """
        pass

    def test_provider_project_development_credential_patch(self):
        """Test case for provider_project_development_credential_patch

        Update provider/development.credential  # noqa: E501
        """
        pass

    def test_provider_project_development_delete(self):
        """Test case for provider_project_development_delete

        Delete provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_domain_create(self):
        """Test case for provider_project_development_domain_create

        Create provider/development.domain  # noqa: E501
        """
        pass

    def test_provider_project_development_domain_delete(self):
        """Test case for provider_project_development_domain_delete

        Delete provider/development.domain  # noqa: E501
        """
        pass

    def test_provider_project_development_domain_get(self):
        """Test case for provider_project_development_domain_get

        Get provider/development.domain  # noqa: E501
        """
        pass

    def test_provider_project_development_domain_list(self):
        """Test case for provider_project_development_domain_list

        List provider/development.domain  # noqa: E501
        """
        pass

    def test_provider_project_development_env_create(self):
        """Test case for provider_project_development_env_create

        Create provider/development.env  # noqa: E501
        """
        pass

    def test_provider_project_development_env_delete(self):
        """Test case for provider_project_development_env_delete

        Delete provider/development.env  # noqa: E501
        """
        pass

    def test_provider_project_development_env_get(self):
        """Test case for provider_project_development_env_get

        Get provider/development.env  # noqa: E501
        """
        pass

    def test_provider_project_development_env_list(self):
        """Test case for provider_project_development_env_list

        List provider/development.env  # noqa: E501
        """
        pass

    def test_provider_project_development_event_get(self):
        """Test case for provider_project_development_event_get

        Get provider/development.event  # noqa: E501
        """
        pass

    def test_provider_project_development_event_list(self):
        """Test case for provider_project_development_event_list

        List provider/development.event  # noqa: E501
        """
        pass

    def test_provider_project_development_get(self):
        """Test case for provider_project_development_get

        Get provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_link_create(self):
        """Test case for provider_project_development_link_create

        Create provider/development.link  # noqa: E501
        """
        pass

    def test_provider_project_development_link_delete(self):
        """Test case for provider_project_development_link_delete

        Delete provider/development.link  # noqa: E501
        """
        pass

    def test_provider_project_development_link_get(self):
        """Test case for provider_project_development_link_get

        Get provider/development.link  # noqa: E501
        """
        pass

    def test_provider_project_development_link_list(self):
        """Test case for provider_project_development_link_list

        List provider/development.link  # noqa: E501
        """
        pass

    def test_provider_project_development_list(self):
        """Test case for provider_project_development_list

        List provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_log_get(self):
        """Test case for provider_project_development_log_get

        Get provider/development.log  # noqa: E501
        """
        pass

    def test_provider_project_development_log_list(self):
        """Test case for provider_project_development_log_list

        List provider/development.log  # noqa: E501
        """
        pass

    def test_provider_project_development_log_read(self):
        """Test case for provider_project_development_log_read

        Read provider/development.log  # noqa: E501
        """
        pass

    def test_provider_project_development_metric_get(self):
        """Test case for provider_project_development_metric_get

        Get provider/development.metric  # noqa: E501
        """
        pass

    def test_provider_project_development_metric_list(self):
        """Test case for provider_project_development_metric_list

        List provider/development.metric  # noqa: E501
        """
        pass

    def test_provider_project_development_metric_point_list(self):
        """Test case for provider_project_development_metric_point_list

        List provider/development.point  # noqa: E501
        """
        pass

    def test_provider_project_development_restart(self):
        """Test case for provider_project_development_restart

        Restart provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_service_get(self):
        """Test case for provider_project_development_service_get

        Get provider/development.service  # noqa: E501
        """
        pass

    def test_provider_project_development_service_list(self):
        """Test case for provider_project_development_service_list

        List provider/development.service  # noqa: E501
        """
        pass

    def test_provider_project_development_sideapp_get(self):
        """Test case for provider_project_development_sideapp_get

        Get provider/development.sideapp  # noqa: E501
        """
        pass

    def test_provider_project_development_sideapp_list(self):
        """Test case for provider_project_development_sideapp_list

        List provider/development.sideapp  # noqa: E501
        """
        pass

    def test_provider_project_development_sideapp_open(self):
        """Test case for provider_project_development_sideapp_open

        Open provider/development.sideapp  # noqa: E501
        """
        pass

    def test_provider_project_development_snapshot_create(self):
        """Test case for provider_project_development_snapshot_create

        Create provider/development.snapshot  # noqa: E501
        """
        pass

    def test_provider_project_development_snapshot_delete(self):
        """Test case for provider_project_development_snapshot_delete

        Delete provider/development.snapshot  # noqa: E501
        """
        pass

    def test_provider_project_development_snapshot_download(self):
        """Test case for provider_project_development_snapshot_download

        Download provider/development.snapshot  # noqa: E501
        """
        pass

    def test_provider_project_development_snapshot_get(self):
        """Test case for provider_project_development_snapshot_get

        Get provider/development.snapshot  # noqa: E501
        """
        pass

    def test_provider_project_development_snapshot_list(self):
        """Test case for provider_project_development_snapshot_list

        List provider/development.snapshot  # noqa: E501
        """
        pass

    def test_provider_project_development_start(self):
        """Test case for provider_project_development_start

        Start provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_stop(self):
        """Test case for provider_project_development_stop

        Stop provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_tag_create(self):
        """Test case for provider_project_development_tag_create

        Create provider/development.tag  # noqa: E501
        """
        pass

    def test_provider_project_development_tag_delete(self):
        """Test case for provider_project_development_tag_delete

        Delete provider/development.tag  # noqa: E501
        """
        pass

    def test_provider_project_development_tag_get(self):
        """Test case for provider_project_development_tag_get

        Get provider/development.tag  # noqa: E501
        """
        pass

    def test_provider_project_development_tag_list(self):
        """Test case for provider_project_development_tag_list

        List provider/development.tag  # noqa: E501
        """
        pass

    def test_provider_project_development_tag_put(self):
        """Test case for provider_project_development_tag_put

        Replace provider/development.tag  # noqa: E501
        """
        pass

    def test_provider_project_development_transfer(self):
        """Test case for provider_project_development_transfer

        Transfer provider/development  # noqa: E501
        """
        pass

    def test_provider_project_development_update(self):
        """Test case for provider_project_development_update

        Update provider/development  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
