"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.tag_array import TagArray
globals()['TagArray'] = TagArray
from h1.model.storage_project_iso_create import StorageProjectIsoCreate


class TestStorageProjectIsoCreate(unittest.TestCase):
    """StorageProjectIsoCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageProjectIsoCreate(self):
        """Test StorageProjectIsoCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageProjectIsoCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
