"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import h1
from h1.api.networking_project_netgw_api import NetworkingProjectNetgwApi  # noqa: E501


class TestNetworkingProjectNetgwApi(unittest.TestCase):
    """NetworkingProjectNetgwApi unit test stubs"""

    def setUp(self):
        self.api = NetworkingProjectNetgwApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_networking_project_netgw_attach(self):
        """Test case for networking_project_netgw_attach

        Attach networking/netgw  # noqa: E501
        """
        pass

    def test_networking_project_netgw_create(self):
        """Test case for networking_project_netgw_create

        Create networking/netgw  # noqa: E501
        """
        pass

    def test_networking_project_netgw_delete(self):
        """Test case for networking_project_netgw_delete

        Delete networking/netgw  # noqa: E501
        """
        pass

    def test_networking_project_netgw_detach(self):
        """Test case for networking_project_netgw_detach

        Detach networking/netgw  # noqa: E501
        """
        pass

    def test_networking_project_netgw_event_get(self):
        """Test case for networking_project_netgw_event_get

        Get networking/netgw.event  # noqa: E501
        """
        pass

    def test_networking_project_netgw_event_list(self):
        """Test case for networking_project_netgw_event_list

        List networking/netgw.event  # noqa: E501
        """
        pass

    def test_networking_project_netgw_get(self):
        """Test case for networking_project_netgw_get

        Get networking/netgw  # noqa: E501
        """
        pass

    def test_networking_project_netgw_list(self):
        """Test case for networking_project_netgw_list

        List networking/netgw  # noqa: E501
        """
        pass

    def test_networking_project_netgw_service_get(self):
        """Test case for networking_project_netgw_service_get

        Get networking/netgw.service  # noqa: E501
        """
        pass

    def test_networking_project_netgw_service_list(self):
        """Test case for networking_project_netgw_service_list

        List networking/netgw.service  # noqa: E501
        """
        pass

    def test_networking_project_netgw_tag_create(self):
        """Test case for networking_project_netgw_tag_create

        Create networking/netgw.tag  # noqa: E501
        """
        pass

    def test_networking_project_netgw_tag_delete(self):
        """Test case for networking_project_netgw_tag_delete

        Delete networking/netgw.tag  # noqa: E501
        """
        pass

    def test_networking_project_netgw_tag_get(self):
        """Test case for networking_project_netgw_tag_get

        Get networking/netgw.tag  # noqa: E501
        """
        pass

    def test_networking_project_netgw_tag_list(self):
        """Test case for networking_project_netgw_tag_list

        List networking/netgw.tag  # noqa: E501
        """
        pass

    def test_networking_project_netgw_tag_put(self):
        """Test case for networking_project_netgw_tag_put

        Replace networking/netgw.tag  # noqa: E501
        """
        pass

    def test_networking_project_netgw_update(self):
        """Test case for networking_project_netgw_update

        Update networking/netgw  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
