"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.provider_env import ProviderEnv
from h1.model.tag_array import TagArray
globals()['ProviderEnv'] = ProviderEnv
globals()['TagArray'] = TagArray
from h1.model.provider_project_development_create import ProviderProjectDevelopmentCreate


class TestProviderProjectDevelopmentCreate(unittest.TestCase):
    """ProviderProjectDevelopmentCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderProjectDevelopmentCreate(self):
        """Test ProviderProjectDevelopmentCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProviderProjectDevelopmentCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
