"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.iam_project_threshold_create import IamProjectThresholdCreate


class TestIamProjectThresholdCreate(unittest.TestCase):
    """IamProjectThresholdCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIamProjectThresholdCreate(self):
        """Test IamProjectThresholdCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IamProjectThresholdCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
