"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.provider_project_development_transfer import ProviderProjectDevelopmentTransfer


class TestProviderProjectDevelopmentTransfer(unittest.TestCase):
    """ProviderProjectDevelopmentTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderProjectDevelopmentTransfer(self):
        """Test ProviderProjectDevelopmentTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProviderProjectDevelopmentTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
