"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.recovery_project_plan_create_retention import RecoveryProjectPlanCreateRetention


class TestRecoveryProjectPlanCreateRetention(unittest.TestCase):
    """RecoveryProjectPlanCreateRetention unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoveryProjectPlanCreateRetention(self):
        """Test RecoveryProjectPlanCreateRetention"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoveryProjectPlanCreateRetention()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
