"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.organisation_billing import OrganisationBilling
globals()['OrganisationBilling'] = OrganisationBilling
from h1.model.iam_organisation_create import IamOrganisationCreate


class TestIamOrganisationCreate(unittest.TestCase):
    """IamOrganisationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIamOrganisationCreate(self):
        """Test IamOrganisationCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IamOrganisationCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
