# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import h1-client-python
from h1-client-python.api.database_project_instance_api import DatabaseProjectInstanceApi  # noqa: E501
from h1-client-python.rest import ApiException


class TestDatabaseProjectInstanceApi(unittest.TestCase):
    """DatabaseProjectInstanceApi unit test stubs"""

    def setUp(self):
        self.api = h1-client-python.api.database_project_instance_api.DatabaseProjectInstanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_database_project_instance_create(self):
        """Test case for database_project_instance_create

        Create database/instance  # noqa: E501
        """
        pass

    def test_database_project_instance_credential_create(self):
        """Test case for database_project_instance_credential_create

        Create database/instance.credential  # noqa: E501
        """
        pass

    def test_database_project_instance_credential_delete(self):
        """Test case for database_project_instance_credential_delete

        Delete database/instance.credential  # noqa: E501
        """
        pass

    def test_database_project_instance_credential_get(self):
        """Test case for database_project_instance_credential_get

        Get database/instance.credential  # noqa: E501
        """
        pass

    def test_database_project_instance_credential_list(self):
        """Test case for database_project_instance_credential_list

        List database/instance.credential  # noqa: E501
        """
        pass

    def test_database_project_instance_credential_patch(self):
        """Test case for database_project_instance_credential_patch

        Update database/instance.credential  # noqa: E501
        """
        pass

    def test_database_project_instance_delete(self):
        """Test case for database_project_instance_delete

        Delete database/instance  # noqa: E501
        """
        pass

    def test_database_project_instance_event_get(self):
        """Test case for database_project_instance_event_get

        Get database/instance.event  # noqa: E501
        """
        pass

    def test_database_project_instance_event_list(self):
        """Test case for database_project_instance_event_list

        List database/instance.event  # noqa: E501
        """
        pass

    def test_database_project_instance_get(self):
        """Test case for database_project_instance_get

        Get database/instance  # noqa: E501
        """
        pass

    def test_database_project_instance_list(self):
        """Test case for database_project_instance_list

        List database/instance  # noqa: E501
        """
        pass

    def test_database_project_instance_service_get(self):
        """Test case for database_project_instance_service_get

        Get database/instance.service  # noqa: E501
        """
        pass

    def test_database_project_instance_service_list(self):
        """Test case for database_project_instance_service_list

        List database/instance.service  # noqa: E501
        """
        pass

    def test_database_project_instance_start(self):
        """Test case for database_project_instance_start

        Start database/instance  # noqa: E501
        """
        pass

    def test_database_project_instance_stop(self):
        """Test case for database_project_instance_stop

        Stop database/instance  # noqa: E501
        """
        pass

    def test_database_project_instance_tag_create(self):
        """Test case for database_project_instance_tag_create

        Create database/instance.tag  # noqa: E501
        """
        pass

    def test_database_project_instance_tag_delete(self):
        """Test case for database_project_instance_tag_delete

        Delete database/instance.tag  # noqa: E501
        """
        pass

    def test_database_project_instance_tag_get(self):
        """Test case for database_project_instance_tag_get

        Get database/instance.tag  # noqa: E501
        """
        pass

    def test_database_project_instance_tag_list(self):
        """Test case for database_project_instance_tag_list

        List database/instance.tag  # noqa: E501
        """
        pass

    def test_database_project_instance_tag_put(self):
        """Test case for database_project_instance_tag_put

        Replace database/instance.tag  # noqa: E501
        """
        pass

    def test_database_project_instance_transfer(self):
        """Test case for database_project_instance_transfer

        Transfer database/instance  # noqa: E501
        """
        pass

    def test_database_project_instance_update(self):
        """Test case for database_project_instance_update

        Update database/instance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
