"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import h1
from h1.api.iam_organisation_policy_api import IamOrganisationPolicyApi  # noqa: E501


class TestIamOrganisationPolicyApi(unittest.TestCase):
    """IamOrganisationPolicyApi unit test stubs"""

    def setUp(self):
        self.api = IamOrganisationPolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_iam_organisation_policy_actor_create(self):
        """Test case for iam_organisation_policy_actor_create

        Create iam/policy.actor  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_actor_delete(self):
        """Test case for iam_organisation_policy_actor_delete

        Delete iam/policy.actor  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_actor_get(self):
        """Test case for iam_organisation_policy_actor_get

        Get iam/policy.actor  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_actor_list(self):
        """Test case for iam_organisation_policy_actor_list

        List iam/policy.actor  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_create(self):
        """Test case for iam_organisation_policy_create

        Create iam/policy  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_delete(self):
        """Test case for iam_organisation_policy_delete

        Delete iam/policy  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_event_get(self):
        """Test case for iam_organisation_policy_event_get

        Get iam/policy.event  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_event_list(self):
        """Test case for iam_organisation_policy_event_list

        List iam/policy.event  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_get(self):
        """Test case for iam_organisation_policy_get

        Get iam/policy  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_list(self):
        """Test case for iam_organisation_policy_list

        List iam/policy  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_service_get(self):
        """Test case for iam_organisation_policy_service_get

        Get iam/policy.service  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_service_list(self):
        """Test case for iam_organisation_policy_service_list

        List iam/policy.service  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_tag_create(self):
        """Test case for iam_organisation_policy_tag_create

        Create iam/policy.tag  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_tag_delete(self):
        """Test case for iam_organisation_policy_tag_delete

        Delete iam/policy.tag  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_tag_get(self):
        """Test case for iam_organisation_policy_tag_get

        Get iam/policy.tag  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_tag_list(self):
        """Test case for iam_organisation_policy_tag_list

        List iam/policy.tag  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_tag_put(self):
        """Test case for iam_organisation_policy_tag_put

        Replace iam/policy.tag  # noqa: E501
        """
        pass

    def test_iam_organisation_policy_update(self):
        """Test case for iam_organisation_policy_update

        Update iam/policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
