"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.iam_project_policy_create_actor import IamProjectPolicyCreateActor
from h1.model.tag_array import TagArray
globals()['IamProjectPolicyCreateActor'] = IamProjectPolicyCreateActor
globals()['TagArray'] = TagArray
from h1.model.iam_project_policy_create import IamProjectPolicyCreate


class TestIamProjectPolicyCreate(unittest.TestCase):
    """IamProjectPolicyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIamProjectPolicyCreate(self):
        """Test IamProjectPolicyCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IamProjectPolicyCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
