"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.tag_array import TagArray
from h1.model.zone_source import ZoneSource
globals()['TagArray'] = TagArray
globals()['ZoneSource'] = ZoneSource
from h1.model.dns_project_zone_create import DnsProjectZoneCreate


class TestDnsProjectZoneCreate(unittest.TestCase):
    """DnsProjectZoneCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDnsProjectZoneCreate(self):
        """Test DnsProjectZoneCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DnsProjectZoneCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
