"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.compute_project_vm_iso_create import ComputeProjectVmIsoCreate


class TestComputeProjectVmIsoCreate(unittest.TestCase):
    """ComputeProjectVmIsoCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComputeProjectVmIsoCreate(self):
        """Test ComputeProjectVmIsoCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ComputeProjectVmIsoCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
