"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.tag_array import TagArray
from h1.model.website_env import WebsiteEnv
globals()['TagArray'] = TagArray
globals()['WebsiteEnv'] = WebsiteEnv
from h1.model.website_project_instance_create import WebsiteProjectInstanceCreate


class TestWebsiteProjectInstanceCreate(unittest.TestCase):
    """WebsiteProjectInstanceCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebsiteProjectInstanceCreate(self):
        """Test WebsiteProjectInstanceCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WebsiteProjectInstanceCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
