"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.provider_agent_resource_event import ProviderAgentResourceEvent


class TestProviderAgentResourceEvent(unittest.TestCase):
    """ProviderAgentResourceEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderAgentResourceEvent(self):
        """Test ProviderAgentResourceEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProviderAgentResourceEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
