"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.networking_project_firewall_update import NetworkingProjectFirewallUpdate


class TestNetworkingProjectFirewallUpdate(unittest.TestCase):
    """NetworkingProjectFirewallUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkingProjectFirewallUpdate(self):
        """Test NetworkingProjectFirewallUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkingProjectFirewallUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
