"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.compute_project_vm_serialport import ComputeProjectVmSerialport


class TestComputeProjectVmSerialport(unittest.TestCase):
    """ComputeProjectVmSerialport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComputeProjectVmSerialport(self):
        """Test ComputeProjectVmSerialport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ComputeProjectVmSerialport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
