# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import h1
from h1.models.iam_project_sa_create import IamProjectSaCreate  # noqa: E501
from h1.rest import ApiException

class TestIamProjectSaCreate(unittest.TestCase):
    """IamProjectSaCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IamProjectSaCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = h1.models.iam_project_sa_create.IamProjectSaCreate()  # noqa: E501
        if include_optional :
            return IamProjectSaCreate(
                name = '0', 
                service = '5e5fc76ff1fb3efe1842336a', 
                tag = [
                    h1.models.tag.tag(
                        id = '0', 
                        key = '0', 
                        value = '0', )
                    ]
            )
        else :
            return IamProjectSaCreate(
                name = '0',
        )

    def testIamProjectSaCreate(self):
        """Test IamProjectSaCreate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
