# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import h1-client-python
from h1-client-python.models.iam_organisation_create import IamOrganisationCreate  # noqa: E501
from h1-client-python.rest import ApiException

class TestIamOrganisationCreate(unittest.TestCase):
    """IamOrganisationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IamOrganisationCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = h1-client-python.models.iam_organisation_create.IamOrganisationCreate()  # noqa: E501
        if include_optional :
            return IamOrganisationCreate(
                name = '0', 
                billing = h1-client-python.models.organisation_billing.Organisation_billing(
                    nip = '0', 
                    email = '0', 
                    company = '0', 
                    currency = 'PLN', 
                    address = h1-client-python.models.billing_address.Billing_address(
                        country = 'PL', 
                        city = '0', 
                        zipcode = '0', 
                        street = '0', ), )
            )
        else :
            return IamOrganisationCreate(
                name = '0',
        )

    def testIamOrganisationCreate(self):
        """Test IamOrganisationCreate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
