"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.tag_array import TagArray
globals()['TagArray'] = TagArray
from h1.model.container_project_registry_create import ContainerProjectRegistryCreate


class TestContainerProjectRegistryCreate(unittest.TestCase):
    """ContainerProjectRegistryCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerProjectRegistryCreate(self):
        """Test ContainerProjectRegistryCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerProjectRegistryCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
