# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import h1
from h1.models.proforma_seller import ProformaSeller  # noqa: E501
from h1.rest import ApiException

class TestProformaSeller(unittest.TestCase):
    """ProformaSeller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProformaSeller
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = h1.models.proforma_seller.ProformaSeller()  # noqa: E501
        if include_optional :
            return ProformaSeller(
                company = '0', 
                address = h1.models.invoice_seller_address.invoice_seller_address(
                    street = '0', 
                    zipcode = '0', 
                    city = '0', 
                    country = '0', ), 
                nip = '0', 
                iban = '0'
            )
        else :
            return ProformaSeller(
                company = '0',
                nip = '0',
                iban = '0',
        )

    def testProformaSeller(self):
        """Test ProformaSeller"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
