"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import h1
from h1.model.quota_limit import QuotaLimit
from h1.model.quota_metric import QuotaMetric
globals()['QuotaLimit'] = QuotaLimit
globals()['QuotaMetric'] = QuotaMetric
from h1.model.quota import Quota


class TestQuota(unittest.TestCase):
    """Quota unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuota(self):
        """Test Quota"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Quota()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
