# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from h1-client-python.configuration import Configuration


class ComputeProjectVmUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user_metadata': 'str',
        'name': 'str'
    }

    attribute_map = {
        'user_metadata': 'userMetadata',
        'name': 'name'
    }

    def __init__(self, user_metadata=None, name=None, local_vars_configuration=None):  # noqa: E501
        """ComputeProjectVmUpdate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._user_metadata = None
        self._name = None
        self.discriminator = None

        if user_metadata is not None:
            self.user_metadata = user_metadata
        if name is not None:
            self.name = name

    @property
    def user_metadata(self):
        """Gets the user_metadata of this ComputeProjectVmUpdate.  # noqa: E501


        :return: The user_metadata of this ComputeProjectVmUpdate.  # noqa: E501
        :rtype: str
        """
        return self._user_metadata

    @user_metadata.setter
    def user_metadata(self, user_metadata):
        """Sets the user_metadata of this ComputeProjectVmUpdate.


        :param user_metadata: The user_metadata of this ComputeProjectVmUpdate.  # noqa: E501
        :type: str
        """

        self._user_metadata = user_metadata

    @property
    def name(self):
        """Gets the name of this ComputeProjectVmUpdate.  # noqa: E501


        :return: The name of this ComputeProjectVmUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ComputeProjectVmUpdate.


        :param name: The name of this ComputeProjectVmUpdate.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComputeProjectVmUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComputeProjectVmUpdate):
            return True

        return self.to_dict() != other.to_dict()
