# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from h1-client-python.configuration import Configuration


class ServiceBilling(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'price': 'ServiceBillingPrice',
        'period': 'str',
        'quantity': 'float',
        'one_time': 'bool',
        'reservations': 'ServiceBillingReservations'
    }

    attribute_map = {
        'price': 'price',
        'period': 'period',
        'quantity': 'quantity',
        'one_time': 'oneTime',
        'reservations': 'reservations'
    }

    def __init__(self, price=None, period=None, quantity=None, one_time=None, reservations=None, local_vars_configuration=None):  # noqa: E501
        """ServiceBilling - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._price = None
        self._period = None
        self._quantity = None
        self._one_time = None
        self._reservations = None
        self.discriminator = None

        if price is not None:
            self.price = price
        if period is not None:
            self.period = period
        if quantity is not None:
            self.quantity = quantity
        if one_time is not None:
            self.one_time = one_time
        if reservations is not None:
            self.reservations = reservations

    @property
    def price(self):
        """Gets the price of this ServiceBilling.  # noqa: E501


        :return: The price of this ServiceBilling.  # noqa: E501
        :rtype: ServiceBillingPrice
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ServiceBilling.


        :param price: The price of this ServiceBilling.  # noqa: E501
        :type: ServiceBillingPrice
        """

        self._price = price

    @property
    def period(self):
        """Gets the period of this ServiceBilling.  # noqa: E501


        :return: The period of this ServiceBilling.  # noqa: E501
        :rtype: str
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this ServiceBilling.


        :param period: The period of this ServiceBilling.  # noqa: E501
        :type: str
        """

        self._period = period

    @property
    def quantity(self):
        """Gets the quantity of this ServiceBilling.  # noqa: E501


        :return: The quantity of this ServiceBilling.  # noqa: E501
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ServiceBilling.


        :param quantity: The quantity of this ServiceBilling.  # noqa: E501
        :type: float
        """

        self._quantity = quantity

    @property
    def one_time(self):
        """Gets the one_time of this ServiceBilling.  # noqa: E501


        :return: The one_time of this ServiceBilling.  # noqa: E501
        :rtype: bool
        """
        return self._one_time

    @one_time.setter
    def one_time(self, one_time):
        """Sets the one_time of this ServiceBilling.


        :param one_time: The one_time of this ServiceBilling.  # noqa: E501
        :type: bool
        """

        self._one_time = one_time

    @property
    def reservations(self):
        """Gets the reservations of this ServiceBilling.  # noqa: E501


        :return: The reservations of this ServiceBilling.  # noqa: E501
        :rtype: ServiceBillingReservations
        """
        return self._reservations

    @reservations.setter
    def reservations(self, reservations):
        """Sets the reservations of this ServiceBilling.


        :param reservations: The reservations of this ServiceBilling.  # noqa: E501
        :type: ServiceBillingReservations
        """

        self._reservations = reservations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceBilling):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServiceBilling):
            return True

        return self.to_dict() != other.to_dict()
