# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from h1-client-python.configuration import Configuration


class ZoneRrsets(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'records': 'str',
        'name': 'str',
        'type': 'str',
        'ttl': 'float'
    }

    attribute_map = {
        'records': 'records',
        'name': 'name',
        'type': 'type',
        'ttl': 'ttl'
    }

    def __init__(self, records=None, name=None, type=None, ttl=None, local_vars_configuration=None):  # noqa: E501
        """ZoneRrsets - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._records = None
        self._name = None
        self._type = None
        self._ttl = None
        self.discriminator = None

        if records is not None:
            self.records = records
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if ttl is not None:
            self.ttl = ttl

    @property
    def records(self):
        """Gets the records of this ZoneRrsets.  # noqa: E501


        :return: The records of this ZoneRrsets.  # noqa: E501
        :rtype: str
        """
        return self._records

    @records.setter
    def records(self, records):
        """Sets the records of this ZoneRrsets.


        :param records: The records of this ZoneRrsets.  # noqa: E501
        :type: str
        """

        self._records = records

    @property
    def name(self):
        """Gets the name of this ZoneRrsets.  # noqa: E501


        :return: The name of this ZoneRrsets.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ZoneRrsets.


        :param name: The name of this ZoneRrsets.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this ZoneRrsets.  # noqa: E501


        :return: The type of this ZoneRrsets.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ZoneRrsets.


        :param type: The type of this ZoneRrsets.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def ttl(self):
        """Gets the ttl of this ZoneRrsets.  # noqa: E501


        :return: The ttl of this ZoneRrsets.  # noqa: E501
        :rtype: float
        """
        return self._ttl

    @ttl.setter
    def ttl(self, ttl):
        """Sets the ttl of this ZoneRrsets.


        :param ttl: The ttl of this ZoneRrsets.  # noqa: E501
        :type: float
        """

        self._ttl = ttl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZoneRrsets):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ZoneRrsets):
            return True

        return self.to_dict() != other.to_dict()
