# coding: utf-8

"""
    HyperOne

    HyperOne API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from h1.configuration import Configuration


class User(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'created_on': 'datetime',
        'modified_on': 'datetime',
        'lang': 'str',
        'phone': 'str',
        'limit': 'UserLimit',
        'uri': 'str',
        'tag': 'list[Tag]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'created_on': 'createdOn',
        'modified_on': 'modifiedOn',
        'lang': 'lang',
        'phone': 'phone',
        'limit': 'limit',
        'uri': 'uri',
        'tag': 'tag'
    }

    def __init__(self, id=None, name=None, created_on=None, modified_on=None, lang='en', phone=None, limit=None, uri=None, tag=None, local_vars_configuration=None):  # noqa: E501
        """User - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._created_on = None
        self._modified_on = None
        self._lang = None
        self._phone = None
        self._limit = None
        self._uri = None
        self._tag = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if created_on is not None:
            self.created_on = created_on
        if modified_on is not None:
            self.modified_on = modified_on
        if lang is not None:
            self.lang = lang
        if phone is not None:
            self.phone = phone
        if limit is not None:
            self.limit = limit
        if uri is not None:
            self.uri = uri
        if tag is not None:
            self.tag = tag

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501


        :return: The id of this User.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.


        :param id: The id of this User.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this User.  # noqa: E501


        :return: The name of this User.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this User.


        :param name: The name of this User.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def created_on(self):
        """Gets the created_on of this User.  # noqa: E501


        :return: The created_on of this User.  # noqa: E501
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this User.


        :param created_on: The created_on of this User.  # noqa: E501
        :type: datetime
        """

        self._created_on = created_on

    @property
    def modified_on(self):
        """Gets the modified_on of this User.  # noqa: E501


        :return: The modified_on of this User.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_on

    @modified_on.setter
    def modified_on(self, modified_on):
        """Sets the modified_on of this User.


        :param modified_on: The modified_on of this User.  # noqa: E501
        :type: datetime
        """

        self._modified_on = modified_on

    @property
    def lang(self):
        """Gets the lang of this User.  # noqa: E501


        :return: The lang of this User.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this User.


        :param lang: The lang of this User.  # noqa: E501
        :type: str
        """
        allowed_values = ["en", "pl"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and lang not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `lang` ({0}), must be one of {1}"  # noqa: E501
                .format(lang, allowed_values)
            )

        self._lang = lang

    @property
    def phone(self):
        """Gets the phone of this User.  # noqa: E501


        :return: The phone of this User.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this User.


        :param phone: The phone of this User.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def limit(self):
        """Gets the limit of this User.  # noqa: E501


        :return: The limit of this User.  # noqa: E501
        :rtype: UserLimit
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this User.


        :param limit: The limit of this User.  # noqa: E501
        :type: UserLimit
        """

        self._limit = limit

    @property
    def uri(self):
        """Gets the uri of this User.  # noqa: E501


        :return: The uri of this User.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this User.


        :param uri: The uri of this User.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def tag(self):
        """Gets the tag of this User.  # noqa: E501


        :return: The tag of this User.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this User.


        :param tag: The tag of this User.  # noqa: E501
        :type: list[Tag]
        """

        self._tag = tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, User):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, User):
            return True

        return self.to_dict() != other.to_dict()
